server {
    listen 8080;
    server_name _;
    absolute_redirect off;

    location = / {
        return 301 /jupyterbook/;
    }

    location = /jupyterbook {
        return 301 /jupyterbook/;
    }

    location ^~ /jupyterbook/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /jupyterbook/index.html;
    }

    location = /uksa-training {
        return 301 /jupyterbook/$is_args$args;
    }

    location ^~ /uksa-training/ {
        rewrite ^/uksa-training/(.*)$ /jupyterbook/$1 permanent;
    }
}
